{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.droibit.plugins.flutter.customtabs",
    "module": "flutter_custom_tabs_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_custom_tabs_android_release-1.0.aar",
          "url": "flutter_custom_tabs_android_release-1.0.aar",
          "size": 69536,
          "sha512": "8f1c5d6136c216bbb26520bae2852254b77d0c6a2db8426874392f49db12e6356550b7535caacfb5946382cb563ce1e008408dab667665d4691b8cd3154c0685",
          "sha256": "f7142c7671f0802fe7a595f0674f466fe62917dadd5fdbedf098d3e2cf3f825f",
          "sha1": "9beae203250f16eae42428e24f171aa9b91db79a",
          "md5": "f8fb3d4af1c267c01fee954867ffe628"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.github.droibit",
          "module": "customtabslauncher",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_custom_tabs_android_release-1.0.aar",
          "url": "flutter_custom_tabs_android_release-1.0.aar",
          "size": 69536,
          "sha512": "8f1c5d6136c216bbb26520bae2852254b77d0c6a2db8426874392f49db12e6356550b7535caacfb5946382cb563ce1e008408dab667665d4691b8cd3154c0685",
          "sha256": "f7142c7671f0802fe7a595f0674f466fe62917dadd5fdbedf098d3e2cf3f825f",
          "sha1": "9beae203250f16eae42428e24f171aa9b91db79a",
          "md5": "f8fb3d4af1c267c01fee954867ffe628"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_custom_tabs_android_release-1.0-sources.jar",
          "url": "flutter_custom_tabs_android_release-1.0-sources.jar",
          "size": 21042,
          "sha512": "a02d035045b3a620bb73b68b8f6991ea948e70497ff68be712dcc5c3af0e9efcb23a46efce81624862cd282eb70d704da69e9e6fcf14797769ad2f32a9d1f89c",
          "sha256": "77d1a159c9ef42b88d68eb425af82a5f6b17d975dd93d4dd754b8db843ba959d",
          "sha1": "47b50aaf9c44dda241ec2b89bc67de29e32d8283",
          "md5": "d0a0fee70f951d00d4aaf38dabd95418"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_custom_tabs_android_release-1.0-javadoc.jar",
          "url": "flutter_custom_tabs_android_release-1.0-javadoc.jar",
          "size": 386100,
          "sha512": "96bb5a00f17689b27fc8e9fa5181449624d79f3855ab35cec97ccf3ac382b47aac6885759fdf848550adf9b99e7d49b3ba9f0bcb1280d49aef770a047604bd36",
          "sha256": "167e100e2e3a8e6483a87539aa976d0d492eda0e272e3dda0b03ed2c2c58e0e6",
          "sha1": "68936e33a70c2cab3665b9342974940cc4708a6f",
          "md5": "2447ee7a923af8a157b79668c7227d35"
        }
      ]
    }
  ]
}
