{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 268160,
          "sha512": "6a5b3f0d1bf97a4c5210de19be4af576b13e13dc75427ed5b5d3f9dc49e07bea9a4ac74f0133a3c2e4a3013036b8d2e1744825410ff8bf3f6c22a1d6a4215221",
          "sha256": "348e4e14bfe97573a8cef887ed641a0d2e67655255e664fb81038342cb6d847b",
          "sha1": "25fb98c5a0e9a4f37d76225091af8b6baa7aa88d",
          "md5": "c14a387bcc0824d1e8249de3dc05e95f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 268160,
          "sha512": "6a5b3f0d1bf97a4c5210de19be4af576b13e13dc75427ed5b5d3f9dc49e07bea9a4ac74f0133a3c2e4a3013036b8d2e1744825410ff8bf3f6c22a1d6a4215221",
          "sha256": "348e4e14bfe97573a8cef887ed641a0d2e67655255e664fb81038342cb6d847b",
          "sha1": "25fb98c5a0e9a4f37d76225091af8b6baa7aa88d",
          "md5": "c14a387bcc0824d1e8249de3dc05e95f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-1.0-sources.jar",
          "url": "webview_flutter_android_release-1.0-sources.jar",
          "size": 58257,
          "sha512": "fa80a1f0620d8a35c218bacae31ea16c38d365445e5dfacf9b45c830b4b0140cee19dfc481618b375aab8fda40605251185d86d5e3c9ebf2f0756270d098a67f",
          "sha256": "836c4e3b88e2494d39177237dce6726b2c2c4d63c8571ae3179036667e76d88e",
          "sha1": "785e831edc37952ffad627bf7b343591dae70857",
          "md5": "ca2801cde56e461b19b8afcef12050a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-1.0-javadoc.jar",
          "url": "webview_flutter_android_release-1.0-javadoc.jar",
          "size": 717444,
          "sha512": "f2a5dc9d3cc41bf5bbaa17b8bf7c89247beee1fcc7b5a913e1a2b92401b2a82e7a041a18d48b9da0385512e0fe127d89e1f161ee20415d8fe9b741c0c4a3f535",
          "sha256": "def0f9e79ef87a06c64eb92f55d73fb88c265eda7ba73fe9a6aad43f7baeefd5",
          "sha1": "a979d59ffa7c3f7f15999fb7fb588839e433fd22",
          "md5": "791cdcc076a10e75eba93cd36fae0459"
        }
      ]
    }
  ]
}
