{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bemobi",
    "module": "smart-checkout",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs_android_release",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_release",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bemobi",
          "module": "plugin_release",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "smart-checkout-0.0.1.aar",
          "url": "smart-checkout-0.0.1.aar",
          "size": 4221442,
          "sha512": "437be4c926c77479cdb38b82f2a1a0a230ebaa90632d1ea80ecfc3fdb1036c1e3ae73c7f9abffd1bacd4e5f44dc1aeaf70538053310886d950636b4411dca485",
          "sha256": "369674d096799097e301895513862000789ff1b91a9b988f49bc52a4c2cbf7e5",
          "sha1": "e7ed6619ef7baf5bf216214c13b1a251a4b166ef",
          "md5": "41dbcbde9866d728633ae5893fc47ebf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs_android_release",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_release",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.bemobi",
          "module": "plugin_release",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "smart-checkout-0.0.1.aar",
          "url": "smart-checkout-0.0.1.aar",
          "size": 4221442,
          "sha512": "437be4c926c77479cdb38b82f2a1a0a230ebaa90632d1ea80ecfc3fdb1036c1e3ae73c7f9abffd1bacd4e5f44dc1aeaf70538053310886d950636b4411dca485",
          "sha256": "369674d096799097e301895513862000789ff1b91a9b988f49bc52a4c2cbf7e5",
          "sha1": "e7ed6619ef7baf5bf216214c13b1a251a4b166ef",
          "md5": "41dbcbde9866d728633ae5893fc47ebf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smart-checkout-0.0.1-sources.jar",
          "url": "smart-checkout-0.0.1-sources.jar",
          "size": 1206,
          "sha512": "40e8828da1e930e8c2ea1674bab78472e961312b05fa66fad899700783611bc8f6f31d5cce768165543e9ca011b340fb0bd7572c8f6445fc5b5aded5003a9039",
          "sha256": "f836cb5d9a99f6f13cb36aa42e0723c411128447ceda3ee928f85527b9c71a50",
          "sha1": "114103677a670d4f3997e60133c44bfec05bd15d",
          "md5": "8ef8781b749fbc4396dc77669cbde966"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smart-checkout-0.0.1-javadoc.jar",
          "url": "smart-checkout-0.0.1-javadoc.jar",
          "size": 261619,
          "sha512": "88e37e19a00ba9fb42bf87c900c2697505a222ea9a86e65e7e8c83f785d859305272ef87dd147ce483d3dc8441b2d401d12a05b0975d654750931e4260a7f1f4",
          "sha256": "f20da8cdebd05f23d36b4d528f812553428c39d873dc436b405306c85b13f75c",
          "sha1": "db3ca144f0f374aebbac3992ea5cd1d1c6be9128",
          "md5": "4352ca4af431b7158d8a29d38a485325"
        }
      ]
    }
  ]
}
