{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bemobi.smart.checkout",
    "module": "bemobi_smart_checkout_plugin_release",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "bemobi_smart_checkout_plugin_release-0.0.1.aar",
          "url": "bemobi_smart_checkout_plugin_release-0.0.1.aar",
          "size": 14870,
          "sha512": "22d5324ae6d8a792978c920685d35ea36e3b215b13953fd687d6f9f1e6b23cc56c4f451a75ebee3a228de2994f67a8e8a74fecf5c89bb5660dacd7e1b07b09e0",
          "sha256": "60364ea88a7dc91a9ac38c1385a4c4ce000306fe588b88ffb4d4f4ab9903e8c9",
          "sha1": "5d18c77c0f753b28a2dfbb8d2f7222798d0cd5b0",
          "md5": "ccfc6c19684ee31dacfc7c795b4fb79f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "bemobi_smart_checkout_plugin_release-0.0.1.aar",
          "url": "bemobi_smart_checkout_plugin_release-0.0.1.aar",
          "size": 14870,
          "sha512": "22d5324ae6d8a792978c920685d35ea36e3b215b13953fd687d6f9f1e6b23cc56c4f451a75ebee3a228de2994f67a8e8a74fecf5c89bb5660dacd7e1b07b09e0",
          "sha256": "60364ea88a7dc91a9ac38c1385a4c4ce000306fe588b88ffb4d4f4ab9903e8c9",
          "sha1": "5d18c77c0f753b28a2dfbb8d2f7222798d0cd5b0",
          "md5": "ccfc6c19684ee31dacfc7c795b4fb79f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bemobi_smart_checkout_plugin_release-0.0.1-sources.jar",
          "url": "bemobi_smart_checkout_plugin_release-0.0.1-sources.jar",
          "size": 3199,
          "sha512": "5d4b4ad69e4d50024cd95abb804b524938ce2368e21827c46f203e32ece3bc16fe201f03b7f26f24a8903fadae884ab5684a7dafeb9bbb4af8544d8ff6877c06",
          "sha256": "11f94baf16b2921d63ac24f834b4ba9de055e380ccb5a979dea5376f740c5429",
          "sha1": "eeee840e43767ad24e7aea08de4aadcb4a01daaf",
          "md5": "3fb8dc82e2009cd7d38d57cc2d9f053c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bemobi_smart_checkout_plugin_release-0.0.1-javadoc.jar",
          "url": "bemobi_smart_checkout_plugin_release-0.0.1-javadoc.jar",
          "size": 285896,
          "sha512": "e21855193401334eeea8a6d162322b217be35a0d341b96eb5245b5250ebb5ce11f696c0f0949727f6005477d62f3318f75cea5e83cdc2104563c6488b99718d0",
          "sha256": "8f2d9132bac224bef6a33403adc6ea9b03b0386ea9059ce03ee58d4d5e6bee96",
          "sha1": "0d665644b8d84dab66ffd1308c480d4b4b19a5d2",
          "md5": "145cfd1f94a4cf4b41b987d45c22f901"
        }
      ]
    }
  ]
}
