{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bemobi",
    "module": "plugin_release",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "plugin_release-0.0.1.aar",
          "url": "plugin_release-0.0.1.aar",
          "size": 20287,
          "sha512": "a86bbc4dc518b7c84261130ecf4435a972aac2afa92d434835c42d2310b8ee6fedede16e8b84e73552bc9e36f4a43e6e53de40d2d3f359f57e1c6dc24bca68bb",
          "sha256": "7cc5bf54b73a063fe3a08d7dbf54e7ad3091037b8737275de37ee76c29ff8d07",
          "sha1": "a061cd708225072d88a07ad2c2cf4e0d0e3b213f",
          "md5": "d321023cee9f928d0e86e3737a46251e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "plugin_release-0.0.1.aar",
          "url": "plugin_release-0.0.1.aar",
          "size": 20287,
          "sha512": "a86bbc4dc518b7c84261130ecf4435a972aac2afa92d434835c42d2310b8ee6fedede16e8b84e73552bc9e36f4a43e6e53de40d2d3f359f57e1c6dc24bca68bb",
          "sha256": "7cc5bf54b73a063fe3a08d7dbf54e7ad3091037b8737275de37ee76c29ff8d07",
          "sha1": "a061cd708225072d88a07ad2c2cf4e0d0e3b213f",
          "md5": "d321023cee9f928d0e86e3737a46251e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin_release-0.0.1-sources.jar",
          "url": "plugin_release-0.0.1-sources.jar",
          "size": 3977,
          "sha512": "7e5dd0861f1f1208559d3cf4e9e1e60cd007b77e1debfe80f85051bfa77e9f6dee4b4bc565b1d84da82c9ded08134a162336483647c422fb521a0466502bbee5",
          "sha256": "98bcd15ad69bde598874b5ad4def5c8d94b38a712f956f3a2be9c91a30e0e4cc",
          "sha1": "7dc459cb90ff1e473c0709c7564dc7fe3bf6830b",
          "md5": "5edd98c6284e42f9be4f279921381603"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin_release-0.0.1-javadoc.jar",
          "url": "plugin_release-0.0.1-javadoc.jar",
          "size": 300045,
          "sha512": "a8b4ac700e33dc299823612c03d8e0a15f3cd4842302784e9a6e98f291f3954d9a83b5fe8d4b4670b2b30e3278ec62c548f380a5dfb2ed464e2fa983f9394b7d",
          "sha256": "5a5c37616972c13634a0cb68aee7244c91d5ff8ea1e08141cf6f2a07c4f41c07",
          "sha1": "c67b9c189cd707d044f5dfdd8aa04103a40219f5",
          "md5": "53d5cbf89979f8cdd118eebf009a02cc"
        }
      ]
    }
  ]
}
