{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bemobi",
    "module": "plugin_release",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "plugin_release-0.0.1.aar",
          "url": "plugin_release-0.0.1.aar",
          "size": 14652,
          "sha512": "d8eb595f827da088d8bd357b1f29758f4480695b4addbc650388394eec840f8b952e2bce00c28f7f76ab2164c9942c3553d096bb3dc4b1c9f97aa58d92ad7623",
          "sha256": "99904c107868339b3d9347898bcc844e82d769878756d1cd41a5dfb125faa579",
          "sha1": "a34da0c1e1115a81911e209ef63d8167c7e374bd",
          "md5": "d165a5650c19dc9f0ef10fc99aa8c29c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "plugin_release-0.0.1.aar",
          "url": "plugin_release-0.0.1.aar",
          "size": 14652,
          "sha512": "d8eb595f827da088d8bd357b1f29758f4480695b4addbc650388394eec840f8b952e2bce00c28f7f76ab2164c9942c3553d096bb3dc4b1c9f97aa58d92ad7623",
          "sha256": "99904c107868339b3d9347898bcc844e82d769878756d1cd41a5dfb125faa579",
          "sha1": "a34da0c1e1115a81911e209ef63d8167c7e374bd",
          "md5": "d165a5650c19dc9f0ef10fc99aa8c29c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin_release-0.0.1-sources.jar",
          "url": "plugin_release-0.0.1-sources.jar",
          "size": 2813,
          "sha512": "7968e7246b1684451905dc4837255a3ff2b143bdd0da946859acf6bcefa2a0743caaa44d64bc2c6177bb4cd86ab1bd5ae548a57f70a184a7ec2bb38c380b2955",
          "sha256": "1cc4bcba828c95fe619f011d348ac7aff2e4a5c7309befe759bed0a361f4c1cb",
          "sha1": "9310954e94b92e1d34a4734e8421e64de9e9ce47",
          "md5": "392cf77179bd69579ca182c1f62ea745"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin_release-0.0.1-javadoc.jar",
          "url": "plugin_release-0.0.1-javadoc.jar",
          "size": 285190,
          "sha512": "7e1ffc7a623aeb0814f8cfd34af91760539c52738a39df0993801e07ffe96a3de32b89c59f8c2273e585d0f56170d243a24fbc6ffd9f7877ea514e9d08dd055d",
          "sha256": "e3890e558c0007ecb6b3d93014c3e1e18b5dc224ae23cd04f888494e7f66cca9",
          "sha1": "7c15633cc6854f12ea8638690e49a6180872e265",
          "md5": "cf51dd721c16be730856b28715b3a62a"
        }
      ]
    }
  ]
}
