{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bemobi.smart.checkout",
    "module": "bemobi_smart_checkout_plugin_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "bemobi_smart_checkout_plugin_release-1.0.aar",
          "url": "bemobi_smart_checkout_plugin_release-1.0.aar",
          "size": 14870,
          "sha512": "22d5324ae6d8a792978c920685d35ea36e3b215b13953fd687d6f9f1e6b23cc56c4f451a75ebee3a228de2994f67a8e8a74fecf5c89bb5660dacd7e1b07b09e0",
          "sha256": "60364ea88a7dc91a9ac38c1385a4c4ce000306fe588b88ffb4d4f4ab9903e8c9",
          "sha1": "5d18c77c0f753b28a2dfbb8d2f7222798d0cd5b0",
          "md5": "ccfc6c19684ee31dacfc7c795b4fb79f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "bemobi_smart_checkout_plugin_release-1.0.aar",
          "url": "bemobi_smart_checkout_plugin_release-1.0.aar",
          "size": 14870,
          "sha512": "22d5324ae6d8a792978c920685d35ea36e3b215b13953fd687d6f9f1e6b23cc56c4f451a75ebee3a228de2994f67a8e8a74fecf5c89bb5660dacd7e1b07b09e0",
          "sha256": "60364ea88a7dc91a9ac38c1385a4c4ce000306fe588b88ffb4d4f4ab9903e8c9",
          "sha1": "5d18c77c0f753b28a2dfbb8d2f7222798d0cd5b0",
          "md5": "ccfc6c19684ee31dacfc7c795b4fb79f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bemobi_smart_checkout_plugin_release-1.0-sources.jar",
          "url": "bemobi_smart_checkout_plugin_release-1.0-sources.jar",
          "size": 3199,
          "sha512": "5d4b4ad69e4d50024cd95abb804b524938ce2368e21827c46f203e32ece3bc16fe201f03b7f26f24a8903fadae884ab5684a7dafeb9bbb4af8544d8ff6877c06",
          "sha256": "11f94baf16b2921d63ac24f834b4ba9de055e380ccb5a979dea5376f740c5429",
          "sha1": "eeee840e43767ad24e7aea08de4aadcb4a01daaf",
          "md5": "3fb8dc82e2009cd7d38d57cc2d9f053c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bemobi_smart_checkout_plugin_release-1.0-javadoc.jar",
          "url": "bemobi_smart_checkout_plugin_release-1.0-javadoc.jar",
          "size": 285884,
          "sha512": "ffa2e50c354e4088272ac110d9f4edf9b64c5b0a7e096244d7e83c9d8845209b2f6f71e19fb8407981b586d1d024789cdd03288fbd159538236a01ba4360167f",
          "sha256": "5833bc0a8e918e59703e9c85f03a296d815fca39371723f0ad10cf63ab5906d8",
          "sha1": "57d39163b4ae6c5757469c33786d2561c43bd5d6",
          "md5": "d366fee3f1f27a953dfd9a31ba82da09"
        }
      ]
    }
  ]
}
