{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bemobi.smart.checkout",
    "module": "smart-checkout",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "com.bemobi.smart.checkout",
          "module": "bemobi_smart_checkout_plugin_release",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs_android_release",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_release",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "smart-checkout-0.0.1.aar",
          "url": "smart-checkout-0.0.1.aar",
          "size": 4222329,
          "sha512": "4025d571ffb79f040bfc61d25ee55e5890ac0ba1d1a19c0644bae2e21dfbf40a9f19467ae521f68d15c5ff2ce13fa640343633c51a040a68d6fa847a3dc205b4",
          "sha256": "732b23d073ba631fcbd208a1335e582dd5e670bb36ee0311b61b42cad2577e90",
          "sha1": "7ec3ae6e9290255569776a582994e08b1560ae7e",
          "md5": "099bad156e6270b25708c79b19aa1dcd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "com.bemobi.smart.checkout",
          "module": "bemobi_smart_checkout_plugin_release",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs_android_release",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_release",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "smart-checkout-0.0.1.aar",
          "url": "smart-checkout-0.0.1.aar",
          "size": 4222329,
          "sha512": "4025d571ffb79f040bfc61d25ee55e5890ac0ba1d1a19c0644bae2e21dfbf40a9f19467ae521f68d15c5ff2ce13fa640343633c51a040a68d6fa847a3dc205b4",
          "sha256": "732b23d073ba631fcbd208a1335e582dd5e670bb36ee0311b61b42cad2577e90",
          "sha1": "7ec3ae6e9290255569776a582994e08b1560ae7e",
          "md5": "099bad156e6270b25708c79b19aa1dcd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smart-checkout-0.0.1-sources.jar",
          "url": "smart-checkout-0.0.1-sources.jar",
          "size": 1218,
          "sha512": "3910f920cb5a6e33f5a851cbe6fa3b0672f781d0931e5590e189a94eb228086a5e7b36b6f78323ba3e9336b6acf3e7590c10f1ac077c0da59c3e20c2b8ea0961",
          "sha256": "b0d7b6c0517b358a903c841c900e4b10be31d4c15197602672fde19d0f001d6f",
          "sha1": "19b9ddc191275601f5019bd54b7cf906d777e7e9",
          "md5": "a64ba0c006960de8796fc5909b266478"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smart-checkout-0.0.1-javadoc.jar",
          "url": "smart-checkout-0.0.1-javadoc.jar",
          "size": 261619,
          "sha512": "88e37e19a00ba9fb42bf87c900c2697505a222ea9a86e65e7e8c83f785d859305272ef87dd147ce483d3dc8441b2d401d12a05b0975d654750931e4260a7f1f4",
          "sha256": "f20da8cdebd05f23d36b4d528f812553428c39d873dc436b405306c85b13f75c",
          "sha1": "db3ca144f0f374aebbac3992ea5cd1d1c6be9128",
          "md5": "4352ca4af431b7158d8a29d38a485325"
        }
      ]
    }
  ]
}
