{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bemobi.smart.checkout",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "com.bemobi.smart.checkout",
          "module": "bemobi_smart_checkout_plugin_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 4222329,
          "sha512": "4025d571ffb79f040bfc61d25ee55e5890ac0ba1d1a19c0644bae2e21dfbf40a9f19467ae521f68d15c5ff2ce13fa640343633c51a040a68d6fa847a3dc205b4",
          "sha256": "732b23d073ba631fcbd208a1335e582dd5e670bb36ee0311b61b42cad2577e90",
          "sha1": "7ec3ae6e9290255569776a582994e08b1560ae7e",
          "md5": "099bad156e6270b25708c79b19aa1dcd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "com.bemobi.smart.checkout",
          "module": "bemobi_smart_checkout_plugin_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.github.droibit.plugins.flutter.customtabs",
          "module": "flutter_custom_tabs_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pay_android",
          "module": "pay_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 4222329,
          "sha512": "4025d571ffb79f040bfc61d25ee55e5890ac0ba1d1a19c0644bae2e21dfbf40a9f19467ae521f68d15c5ff2ce13fa640343633c51a040a68d6fa847a3dc205b4",
          "sha256": "732b23d073ba631fcbd208a1335e582dd5e670bb36ee0311b61b42cad2577e90",
          "sha1": "7ec3ae6e9290255569776a582994e08b1560ae7e",
          "md5": "099bad156e6270b25708c79b19aa1dcd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0-sources.jar",
          "url": "flutter_release-1.0-sources.jar",
          "size": 1218,
          "sha512": "3910f920cb5a6e33f5a851cbe6fa3b0672f781d0931e5590e189a94eb228086a5e7b36b6f78323ba3e9336b6acf3e7590c10f1ac077c0da59c3e20c2b8ea0961",
          "sha256": "b0d7b6c0517b358a903c841c900e4b10be31d4c15197602672fde19d0f001d6f",
          "sha1": "19b9ddc191275601f5019bd54b7cf906d777e7e9",
          "md5": "a64ba0c006960de8796fc5909b266478"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0-javadoc.jar",
          "url": "flutter_release-1.0-javadoc.jar",
          "size": 261616,
          "sha512": "5b64cd42625ec2c75c9437f18bd3e5c69969556ad3c068ca7bd0242f8c7d23ce6c65d2f8097e005e229d5f241d05929b5c0bf94caa334d45fd2f8e456b2c347f",
          "sha256": "3c5197d7e5a0df80632c6be2dcc3d32fe22a7c0acd3b7be2fa4d01973e5759b0",
          "sha1": "acd5578a961c4af43f01bb0d35115becc8c2d530",
          "md5": "4fdbf6eb2ad0e81958a11cf3a2e9d327"
        }
      ]
    }
  ]
}
