{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-0.0.1.aar",
          "url": "webview_flutter_android_release-0.0.1.aar",
          "size": 268160,
          "sha512": "6a5b3f0d1bf97a4c5210de19be4af576b13e13dc75427ed5b5d3f9dc49e07bea9a4ac74f0133a3c2e4a3013036b8d2e1744825410ff8bf3f6c22a1d6a4215221",
          "sha256": "348e4e14bfe97573a8cef887ed641a0d2e67655255e664fb81038342cb6d847b",
          "sha1": "25fb98c5a0e9a4f37d76225091af8b6baa7aa88d",
          "md5": "c14a387bcc0824d1e8249de3dc05e95f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-0.0.1.aar",
          "url": "webview_flutter_android_release-0.0.1.aar",
          "size": 268160,
          "sha512": "6a5b3f0d1bf97a4c5210de19be4af576b13e13dc75427ed5b5d3f9dc49e07bea9a4ac74f0133a3c2e4a3013036b8d2e1744825410ff8bf3f6c22a1d6a4215221",
          "sha256": "348e4e14bfe97573a8cef887ed641a0d2e67655255e664fb81038342cb6d847b",
          "sha1": "25fb98c5a0e9a4f37d76225091af8b6baa7aa88d",
          "md5": "c14a387bcc0824d1e8249de3dc05e95f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-0.0.1-sources.jar",
          "url": "webview_flutter_android_release-0.0.1-sources.jar",
          "size": 58257,
          "sha512": "fa80a1f0620d8a35c218bacae31ea16c38d365445e5dfacf9b45c830b4b0140cee19dfc481618b375aab8fda40605251185d86d5e3c9ebf2f0756270d098a67f",
          "sha256": "836c4e3b88e2494d39177237dce6726b2c2c4d63c8571ae3179036667e76d88e",
          "sha1": "785e831edc37952ffad627bf7b343591dae70857",
          "md5": "ca2801cde56e461b19b8afcef12050a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-0.0.1-javadoc.jar",
          "url": "webview_flutter_android_release-0.0.1-javadoc.jar",
          "size": 718056,
          "sha512": "97f259a04707c0c1e1a1c8d6191cb65ca4a17366481430bb637d3fdb151ce25fb50477e523304a3b88e1dc973ac173596ff64f9dd15401d74adb1f5d6cfb4d35",
          "sha256": "5df5e1e19d6707f87d64d1180c01a2045431f4d51fd3d5b0eb81ed25acd83e0b",
          "sha1": "bbd8054c614d9d0ad451b0d119a606ebdea971e8",
          "md5": "fb6cf0646b5d1169fbb57eaa41ac5da5"
        }
      ]
    }
  ]
}
