{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.droibit.plugins.flutter.customtabs",
    "module": "flutter_custom_tabs_android_release",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_custom_tabs_android_release-0.0.1.aar",
          "url": "flutter_custom_tabs_android_release-0.0.1.aar",
          "size": 69536,
          "sha512": "8f1c5d6136c216bbb26520bae2852254b77d0c6a2db8426874392f49db12e6356550b7535caacfb5946382cb563ce1e008408dab667665d4691b8cd3154c0685",
          "sha256": "f7142c7671f0802fe7a595f0674f466fe62917dadd5fdbedf098d3e2cf3f825f",
          "sha1": "9beae203250f16eae42428e24f171aa9b91db79a",
          "md5": "f8fb3d4af1c267c01fee954867ffe628"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.github.droibit",
          "module": "customtabslauncher",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_custom_tabs_android_release-0.0.1.aar",
          "url": "flutter_custom_tabs_android_release-0.0.1.aar",
          "size": 69536,
          "sha512": "8f1c5d6136c216bbb26520bae2852254b77d0c6a2db8426874392f49db12e6356550b7535caacfb5946382cb563ce1e008408dab667665d4691b8cd3154c0685",
          "sha256": "f7142c7671f0802fe7a595f0674f466fe62917dadd5fdbedf098d3e2cf3f825f",
          "sha1": "9beae203250f16eae42428e24f171aa9b91db79a",
          "md5": "f8fb3d4af1c267c01fee954867ffe628"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_custom_tabs_android_release-0.0.1-sources.jar",
          "url": "flutter_custom_tabs_android_release-0.0.1-sources.jar",
          "size": 21042,
          "sha512": "a02d035045b3a620bb73b68b8f6991ea948e70497ff68be712dcc5c3af0e9efcb23a46efce81624862cd282eb70d704da69e9e6fcf14797769ad2f32a9d1f89c",
          "sha256": "77d1a159c9ef42b88d68eb425af82a5f6b17d975dd93d4dd754b8db843ba959d",
          "sha1": "47b50aaf9c44dda241ec2b89bc67de29e32d8283",
          "md5": "d0a0fee70f951d00d4aaf38dabd95418"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_custom_tabs_android_release-0.0.1-javadoc.jar",
          "url": "flutter_custom_tabs_android_release-0.0.1-javadoc.jar",
          "size": 386151,
          "sha512": "7c708300a6dba8c3e7b4a3b72ca79568fcc380bfc6fe04c4a6bd7a7621deb76528ecc5243bdc799912c2ba62d7b22894571d8e5d694107ffcbf4459933c5d265",
          "sha256": "8e39a6923c00428da7c3d45c29fc5d92b3c7c25e6f6485fa934ed2998dfc52c7",
          "sha1": "df9fd4fcd2c44edf8b6fe8a2a4289560f3f48393",
          "md5": "ed0fa874bb43ad6ccf4b8434c1ff6706"
        }
      ]
    }
  ]
}
