{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bemobi",
    "module": "plugin_release",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "plugin_release-0.0.1.aar",
          "url": "plugin_release-0.0.1.aar",
          "size": 20127,
          "sha512": "6a181488f8b9aa94f4d6f5a77ab6a5f019b26e20671eb81feaf23862819609b63996b7731eb23ac1dc177dc5b519ee866dff6c46d3c14c5124d7c35e1ea3f899",
          "sha256": "37a01791fea12400d5ac6871b6b9e9cd7e17566e326258355e36dc90a3c59768",
          "sha1": "976dc717366f131a6646d1490af00f165bdb4f69",
          "md5": "2bdf48a36df117b78f503b84c422ec55"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "plugin_release-0.0.1.aar",
          "url": "plugin_release-0.0.1.aar",
          "size": 20127,
          "sha512": "6a181488f8b9aa94f4d6f5a77ab6a5f019b26e20671eb81feaf23862819609b63996b7731eb23ac1dc177dc5b519ee866dff6c46d3c14c5124d7c35e1ea3f899",
          "sha256": "37a01791fea12400d5ac6871b6b9e9cd7e17566e326258355e36dc90a3c59768",
          "sha1": "976dc717366f131a6646d1490af00f165bdb4f69",
          "md5": "2bdf48a36df117b78f503b84c422ec55"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin_release-0.0.1-sources.jar",
          "url": "plugin_release-0.0.1-sources.jar",
          "size": 2491,
          "sha512": "fd7e35cd12fb9526ef4cfac99139a0bf2a5ae6ebe8ea1e6e33534e8b75ed8c734b7f2a99db2f2e7db2a81c66411eae9e4312a8ec92353050e4cfce21090f4717",
          "sha256": "308d6d7f46ab8aff8f72ad1b1f16b9b1e9d2258578c5ed3233dea0eb7bba4b62",
          "sha1": "1b70b475f13eab4e3969f36deec90b4aa82507bb",
          "md5": "c490c36269dafde648401d82114866b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin_release-0.0.1-javadoc.jar",
          "url": "plugin_release-0.0.1-javadoc.jar",
          "size": 296263,
          "sha512": "1b7e0429d9d2739e917441ff31eb13a00495c45628d916b4243a1c4b1b289fd0051c3e0dc187827b85233eb57fab43af0aa1726b79ef981adfe6f2c07fdcd75d",
          "sha256": "8bc705f8663e1694ddc383cd5bb09e435c77424a2455deb9cfc16653294bc8f9",
          "sha1": "40633f7e54dec91425281ab752b29985bb9848c2",
          "md5": "8170725cd0fa35a8b2d10fbcd6f4681c"
        }
      ]
    }
  ]
}
